
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Feb 22 17:36:52 CET 2023
//----------------------------------------------------

package zoot.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int FONCTIONS = 5;
  public static final int ECRIRE = 7;
  public static final int IDF = 12;
  public static final int DEBUT = 2;
  public static final int PARO = 9;
  public static final int POINTVIRGULE = 6;
  public static final int RETOURNER = 11;
  public static final int FIN = 3;
  public static final int EOF = 0;
  public static final int VARIABLES = 4;
  public static final int CSTBOOLEENNE = 14;
  public static final int EGAL = 8;
  public static final int ENTIER = 15;
  public static final int PARF = 10;
  public static final int error = 1;
  public static final int CSTENTIERE = 13;
  public static final int BOOLEEN = 16;
}

